export const SYS_CONSTANT = {
  AUTH_TOKEN: 'AUTH_TOKEN',
}

export const DICT_FIELDS = [
  'COMM_MODE',
  'PROTOCOL_TYPE',
  'PHASE_LINE',
  'BAUDRATE',
  'WIRING_MODE_TYPE',
  'ORGINDUSTRY_TYPE',
  'CUSTOMER_TYPE',
  'ENERGY_TYPE',
] as const
